# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  
steps:
- task: UseDotNet@2

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3'
    includePreviewVersions: true
- task: NuGetToolInstaller@0
- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'