version: '3'

services:
  api:
    image: backend
    build:
      context: .
    ports:
      - "8000:5000"
      # ext : docker-image
    networks:
      - backend-network
networks:
    backend-network:
        driver: nat
