version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    networks:
      - backend-network
networks:
    backend-network:
        driver: bridge
